name: _countdowns
description: "IT'S THE FINAL COUNTDOWN"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0
  audioplayers: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/digital-7/
    - assets/images/wedding-couple.png
    - assets/images/leave.png
    - assets/sound/zagrota.mp3
    - assets/sound/goodbye.mp3

  fonts:
    - family: Digital7Mono
      fonts:
        - asset: assets/fonts/digital-7/digital-7 (mono).ttf
